### ISSUE TITLE
Check .py code against pep8

### ISSUE THREAD

**Issue by runjak** [lingdb/soundcomparisons#257]
[Pep8](https://www.python.org/dev/peps/pep-0008/) is the usual convention to structure python code by,
and with an automated [checker](https://github.com/PyCQA/pep8) for it there is not much excuse for me to ignore it. I should therefore adapt pep8 style in the future.

**Comment by runjak** [comment]
I've tried this a bit with 41d29d2327b1b581d421991f1c0101dc3e3089e8 and though it appears to be some work I think it will work out fine and more consistent than code currently is.

**Comment by xrotwang** [comment]
I've added some configuration for `flake8` in `setup.cfg`, so running `flake8 soundcomparisons` gives us a list of pep8 violations to work on.

**Comment by runjak** [comment]
Ok @xrotwang, so the project passes the flake8 test on the `devel` branch now.
I removed the import of `config` in e1314747b43ffe25724d997b4c55c651d0b21867 because the test was remarking that the import was unused.
If you could confirm that this import was indeed unnecessary I would merge devel into master and close this issue.

**Comment by runjak** [comment]
Äh, sorry - maybe that wasn't a clever question ^^
I'll mark this issue as closed.

**Comment by runjak** [comment]
There are apparently different cases of too long lines that I still have to fix. I missed these cases because of misuse of `flake8` on my side.
