### ISSUE TITLE
New Boolean field 'MISSING'

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/soundcomparisons#277]
We need to move to a system where all sound files have an explicit record in the database, without the programme having to try to guess.
The transcriptions data table needs a new boolean field called something like 'Missing from recording'.  Once Jakob can give Paul the field name, the Excel SQL output code needs to be changed so that where the transcriber writes 'MISSING' in the phonetic transcription cell, the 'Missing from recording' field in the SQL output is set to TRUE.  Otherwise, it will be left as false, but perhaps this does not need specifying in the SQL output.  Please confirm the SQL output syntax needed.
Hans-Jörg and Scott will then also need to adapt their scripts for outputting SQL files from TextGrids.

**Comment by runjak** [comment]
The field has been added  to the `Transcriptions_<studyName>` tables,
and has the name `IsMIssing`.
It is of type `BOOL` and thus accepts the values `0` and `1`.
A value of `NULL` will not be accepted, but will instead result in the entry having `0` as it's value.
This is live as of now, so it may also be of interest to @Bibiko.
I'll write a mail to notify Scott.
This change is only in the database for now and is not reflected by the behavior of the website in any way. The only noticeable difference is that an `IsMIssing` field will also be provided via in the JSON.

**Comment by runjak** [comment]
After discussion with @PaulHeggarty I understood that the name `IsMissing` may be misleading.
So I renamed this field to `RecordingMissing`.
