### ISSUE TITLE
Fix translation interface missing/changed parts

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/soundcomparisons#280]
Edited by @runjak:
The translation target terms should be set to the English 'translation', not the initial text from the database.

**Comment by runjak** [comment]
At least for the dynamic translations, the following should work:
When I change `one` in the English translation:
![change1](https://cloud.githubusercontent.com/assets/5417642/12720514/8e5d5158-c8fb-11e5-8681-3ea0e3f1ff13.png)
I get this for `Changed translation` for the German translation:
![change2](https://cloud.githubusercontent.com/assets/5417642/12720515/9076ccbc-c8fb-11e5-8f06-aec475f740d0.png)

**Comment by runjak** [comment]
This observation also holds for static translations:
![change1](https://cloud.githubusercontent.com/assets/5417642/12720659/1edd085e-c8fc-11e5-9773-a8efb5ef189a.png)
![change2](https://cloud.githubusercontent.com/assets/5417642/12720663/21292372-c8fc-11e5-8110-5caf3cdae5ad.png)

**Comment by runjak** [comment]
A problem I find with the current approach of `Changed translations` is that I cannot mark things as `still OK`. Instead I have to edit the field a bit focus somewhere else and than put the old stuff back in. Just so that I can store the 'new' change and thereby update the thing.

**Comment by runjak** [comment]
So it was clarified to me that this is a problem with the basic categories, and not as I thought with the `Special cases`. Also the `Still OK` button will be a implemented when solving this.

**Comment by runjak** [comment]
The interesting parts to fix here are in `admin/query/translationColumnProjection.php`:
* [TranslationColumnProjection,page(…)](https://github.com/lingdb/soundcomparisons/blob/php/admin/query/translationColumnProjection.php#L159-L208)
* [TranslationColumnProjection.search(…)](https://github.com/lingdb/soundcomparisons/blob/php/admin/query/translationColumnProjection.php#L223-L321)

**Comment by runjak** [comment]
So the general problem here is fixed and can be deployed.
I'll look into the `Still OK` button before deployment.
Also I decided that when viewing the English translation, we want to see the entry from the database rather than the English entry itself because it gives more (useful) information.
